version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3300:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=test
      - MYSQL_USER=user
      - MYSQL_DATABASE=task